### ISSUE TITLE
Publish `*.spkg` during new releases

### ISSUE THREAD

**Issue by DenisCarriere** [streamingfast/substreams-sink-kv#7]
Publish `*.spkg` during new releases to allow `import` of Protobuf messages

**substreams.yaml**
```yaml
imports:
  sink_kv: https://github.com/streamingfast/substreams-sink-kv/releases/download/v0.1.2/substreams-sink-kv-v0.1.2.spkg

modules:
  - name: kv_out
    kind: map
    inputs:
      - map: map_example
    output:
      type: proto:sf.substreams.sink.kv.v1.KVOperations
```
